"use client";

import MainMap from "@/components/mainMap/MainMap";
import type { Metadata } from "next";
import "./globals.scss";
import "mapbox-gl/dist/mapbox-gl.css";
import GeneralProvider from "@/components/generalProvider/GeneralProvider";
import { useState } from "react";

export const metadata: Metadata = {
  title: "Hooper",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const [isLoadingScreen, setIsLoadingScreen] = useState(true);

  return (
    <html lang="ua">
      <body className="w-screen h-screen relative">
        <GeneralProvider>
          <MainMap />
          {children}
        </GeneralProvider>
      </body>
    </html>
  );
}
